### PR TITLE
List orders and items

### PR DESCRIPTION
**Pull request by mangorr**

### CODE REVIEW

**Comment by zhedebut03** [comment]
Please connect the pull request to the corresponding issue.

If your pull request is beyond the content of the story, please revise/comment on the story to provide some supplementary content, or create another new story.

Thank you!

**Comment by zhedebut03** [comment]
Please pull the latest change before pushing your part. Appreciated!

**Comment by mangorr** [comment]
> Please pull the latest change before pushing your part. Appreciated!

Relevant story update and code improvement have done.

**Comment by zhedebut03** [comment]
Note: (could add test case)
test models --> list all items

**Review by zhedebut03 — COMMENTED** [review]
Note: 
(could add test case) test models --> list all items

**Pull request merged**
